[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.9.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "zola build --base-url $DEPLOY_PRIME_URL"

# Redirect rules
[[redirects]]
  from = "https://joehaines.uk/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

[[redirects]]
  from = "https://www.joehaines.uk/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

[[redirects]]
  from = "https://joehaines.netlify.com/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

[[redirects]]
  from = "https://www.joehaines.netlify.com/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

# We used to have an RSS feed at "feed.xml", but now it's at "rss.xml"
[[redirects]]
  from = "https://www.joehaines.co.uk/feed.xml"
  to = "https://www.joehaines.co.uk/rss.xml"
  force = true

# Headers
[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' https://*.cloudfront.net; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; block-all-mixed-content"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
