[build]
publish = "public"
command = "curl -sL https://github.com/getzola/zola/releases/download/v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./zola build"

[context.deploy-preview]
command = "curl -sL https://github.com/getzola/zola/releases/download/v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./zola build --base-url $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "curl -sL https://github.com/getzola/zola/releases/download/v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./zola build --base-url $DEPLOY_PRIME_URL"

# Redirect rules
[[redirects]]
  from = "https://joehaines.uk/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

[[redirects]]
  from = "https://www.joehaines.uk/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

[[redirects]]
  from = "https://joehaines.netlify.com/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

[[redirects]]
  from = "https://www.joehaines.netlify.com/*"
  to = "https://www.joehaines.co.uk/:splat"
  force = true

# Headers
[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'none'; style-src 'self'; img-src 'self' https://*.cloudfront.net; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; block-all-mixed-content"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
